server:
  port: 8080
  servlet:
    context-path: /test
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bnk?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: wu19990306

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  transaction:
    rollback-on-commit-failure: true


#graphql:
#  servlet:
#    mapping: /resources/graphql
#    enabled: true
#    corsEnabled: true





#server:
#  address: 0.0.0.0
#  port: 10001
#  sessionTimeout: 3600
#
#spring:
#  application:
#    name: ${artifactId}
#    index: /
